export const BRANCHES = [
  {
    id: 'dongtan',
    title: '화성동탄점',
    badge: '본점',
    region: '경기 화성',
    phoneNumber: '010-8381-0431',
    description: '고운황금손 화성동탄 본점입니다.',
    address: '경기도 화성시 향남읍 상신하길로',
    naverPlaceUrl: 'https://naver.me/FBepMjL3',
    images: ['/franchisee/dongtan_1.jpeg', '/franchisee/dongtan_2.jpeg', '/franchisee/dongtan_3.jpeg'] as [
      string,
      string,
      string,
    ],
  },
  {
    id: 'suwon',
    title: '수원점',
    badge: '지점',
    region: '경기 수원',
    phoneNumber: '010-5536-3765',
    description: '고운황금손 수원점입니다.',
    address: '경기도 수원시 팔달구 인계로',
    naverPlaceUrl: 'https://naver.me/xpB4oXiI',
    images: ['/franchisee/suwon_1.jpeg', '/franchisee/suwon_2.jpeg', '/franchisee/suwon_3.jpeg'] as [
      string,
      string,
      string,
    ],
  },
  {
    id: 'yongin',
    title: '용인점',
    badge: '지점',
    region: '경기 용인',
    phoneNumber: '0507-1381-7533',
    description: '고운황금손 용인점입니다.',
    address: '경기 용인시 기흥구 죽전로',
    naverPlaceUrl: 'https://naver.me/5VxlOdcK',
    images: ['/franchisee/yongin_1.jpeg', '/franchisee/yongin_2.jpeg', '/franchisee/yongin_3.png'] as [
      string,
      string,
      string,
    ],
  },
];
