export { Comment } from '../../widgets/Comment/ui/Comment';
export { ReservationApplyPage } from './apply/ui/ReservationApplyPage';
export { FAQItemList, orderCardList } from './config/const';
export { getConsultDetailData } from './detail/api/loader';
export { ReservationDetailPage } from './detail/ui/ReservationDetailPage';
export { getReservationListData } from './list/api/loader';
export { ReservationListPage } from './list/ui/ReservationListPage';
export { ReservationPagination } from './list/ui/ReservationPagination';
export { FAQItem } from './ui/FAQItem';
export { OrderCard } from './ui/OrderCard';
export { ReservationCard } from './ui/ReservationCard';
export { ReservationPage } from './ui/reservationPage';
